### PR TITLE
Adds October 2015 materials

### PR DESCRIPTION
**Pull request by iteles**
## DO NOT MERGE YET!

Currently:
+ Adds October directory link to readme
+ Adds speaker materials for 5 speakers, 2 missing
+ ~~Newsletter still missing~~ No newsletter was written this month

### CODE REVIEW

**Comment by iteles** [comment]
Hi @RabeaGleissner!

This isn't ready to merge yet, we're still missing half of the October materials but I pushed it up so that if you want you can commit your meetup notes to this branch and all of the October stuff will go in at once without merge conflicts when it's ready :wink:

**Comment by RabeaGleissner** [comment]
Hi @iteles, 
Thanks, sounds good. I'll aim to do it over the weekend.

**Comment by RabeaGleissner** [comment]
Hi @iteles, 
Notes added!
I also noticed that Katerina must have removed her slides from Slideshare, so I removed the broken link for now.

**Comment by iteles** [comment]
:+1: Good spot! Thanks for these :blush:

**Comment by iteles** [comment]
@RabeaGleissner I think it may be time to merge this branch in so that there is _something_ up for October. We can always add to it later.

Hope it all went well today!

**Pull request merged**
